### ISSUE TITLE
Add identity check for proposed PRs within orga membership

### ISSUE THREAD

**Issue by MarkusTiede** [baloise-incubator/org#14]
We should automatically check the requirements we have in our guidelines e.g such as the committer ID (eMail).

At the moment this is manually done and error prone e.g. see : https://github.com/baloise-incubator/org/commit/7f32181c06402da7532c31d8553b55eaebe6e96e.patch

**Comment by MarkusTiede** [comment]
Also we should check that each contributor is filing a PR for him- / herself .

**Comment by christiansiegel** [comment]
Just an idea..
```bash
COMMITTER_EMAIL=$(git log -1 $TRAVIS_COMMIT --pretty="%cE")
if [[ ! $COMMITTER_EMAIL =~ ^[a-z.]+@baloise\.[a-z]{2,3}$ ]]
then
   echo "Commit with invalid email (should be '@baloise.TLD'): $COMMITTER_EMAIL"
   exit 1
fi
```
